nodeLinker: node-modules

# eslint-plugin-import v2.x only declares peer support up to eslint v9;
# silence the noise — the plugin works correctly with eslint v10 at runtime.
logFilters:
  - code: YN0060
    text: "eslint-plugin-import"
    level: discard
  - code: YN0086
    level: discard
  - code: YN0069
    text: "eslint-plugin-import"
    level: discard
