import type { TTransform } from './types';

/**
 * Groups array elements by a key generated by a provided function.
 * @param array The array to group.
 * @param keyFn TTransform function that returns the grouping key for each element.
 * @returns An object with keys as group names and values as arrays of grouped elements.
 * @example
 * const items = [{ category: 'fruit', name: 'apple' }, { category: 'vegetable', name: 'carrot' }];
 * const grouped = ArrayGroupBy(items, item => item.category);
 * // grouped.fruit is [{ category: 'fruit', name: 'apple' }]
 */
export function ArrayGroupBy<T, K extends string | number | symbol>(array: T[], keyFn: TTransform<T, K>): Record<K, T[]> {
	if (!array) {
		return {} as Record<K, T[]>;
	}

	return array.reduce((acc, item) => {
		const key = keyFn(item);
		if (!acc[key]) {
			acc[key] = [];
		}
		acc[key].push(item);
		return acc;
	}, {} as Record<K, T[]>);
}
