import type { TTransform } from './types';

/**
 * Groups array elements by a key generated by a provided function.
 *
 * @template T - The type of array elements
 * @template K - The key type (string, number, or symbol)
 * @param array - The array to group
 * @param keyFn - Function that returns the grouping key for each element
 * @returns A record where each key maps to an array of matching elements
 *
 * @example
 * ```typescript
 * const items = [{ category: 'fruit', name: 'apple' }, { category: 'vegetable', name: 'carrot' }];
 * ArrayGroupBy(items, (item) => item.category);
 * // { fruit: [{ category: 'fruit', name: 'apple' }], vegetable: [{ category: 'vegetable', name: 'carrot' }] }
 *
 * ArrayGroupBy(['one', 'two', 'three'], (s) => s.length);
 * // { 3: ['one', 'two'], 5: ['three'] }
 * ```
 */
export function ArrayGroupBy<T, K extends string | number | symbol>(array: T[], keyFn: TTransform<T, K>): Record<K, T[]> {
	if (!array) {
		return {} as Record<K, T[]>;
	}

	return array.reduce((acc, item) => {
		const key = keyFn(item);
		if (!acc[key]) {
			acc[key] = [];
		}
		acc[key].push(item);
		return acc;
	}, {} as Record<K, T[]>);
}
